# Generated by Django 5.0.7 on 2024-07-28 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("new_project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="Contact",
            new_name="contact",
        ),
    ]
