# Generated by Django 5.0.7 on 2024-07-28 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("new_project", "0002_rename_contact_contact_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="contact",
        ),
    ]
